#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 28 21:12:29 2017

@author: notSeabasschin
"""

x = int(input('Enter an integer: '))
if x%2 == 0:
    print('')
    print('Even')
else:
    print('')
    print('Odd')
print('Done with conditional')


if x%2 == 0:
    if x%3 == 0:
        print('x is divisible by 2 and 3')
    else: 
        print('x is divisible by 2 and not 3')
else x%3 == 0:
    ('x is divisble by 3 and not 2')